ITALIAN_VENUES = {
    'Chievo Verona': 'Marcantonio Bentegodi',
    'Lazio': 'Olimpico di Roma',
    'Bologna': 'Stadio Renato Dall Ara',
    'Empoli': 'Carlo Castellani',
    'Parma': 'Ennio Tardini',
    'Sassuolo': 'Mapei Stadium - Città del Tricolore',
    'Torino': 'Stadio Grande Torino',
    'Atalanta': 'Gewiss Stadium',
    'Juventus': 'Allianz Stadium',
    'Napoli': 'Stadio Diego Armando Maradona',
    'Cagliari': 'Unipol Domus',
    'Fiorentina': 'Artemio Franchi',
    'Frosinone': 'Benito Stirpe',
    'Genoa': 'Luigi Ferraris',
    'Internazionale': 'Giuseppe Meazza',
    'SPAL': 'Paolo Mazza',
    'Udinese': 'Dacia Arena',
    'AS Roma': 'Olimpico di Roma',
    'AC Milan': 'Giuseppe Meazza',
    'Sampdoria': 'Luigi Ferraris',
    'Hellas Verona': 'Marcantonio Bentegodi',
    'Lecce': 'Ettore Giardiniero',
    'Brescia': 'Mario Rigamonti',
    'Spezia': 'Alberto Picco',
    'Crotone': 'Ezio Scida',
    'Benevento': 'Ciro Vigorito'
}